### ISSUE TITLE
Control requests failing

### ISSUE THREAD

**Issue by codepend** [gavsto/AutomateAPI#54]
I am receiving the following error when running any comparison, for example: Get-AutomateComputer -NotSeenInDays 30 | Compare-AutomateControlStatus

The Control Server is version: 20.11.1622.7619

```
PS C:\Users\demo\Documents\GitHub\AutomateAPI> Get-AutomateComputer -NotSeenInDays 30 | Compare-AutomateControlStatus
Checking to see if the recommended Internal Monitor is present
Internal Monitor is present
Invoke-ControlAPIMaster : An error has been thrown.
at Invoke-ControlAPIMaster<Process>, C:\Users\demo\Documents\GitHub\AutomateAPI\Public\Invoke-ControlAPIMaster.ps1: line 91
at Get-ControlSession<End>, C:\Users\demo\Documents\GitHub\AutomateAPI\Public\Get-ControlSession.ps1: line 165
at Compare-AutomateControlStatus<End>, C:\Users\demo\Documents\GitHub\AutomateAPI\Public\Compare-AutomateControlStatus.ps1: line 127
at <ScriptBlock>, <No file>: line 1
-->
--> Incorrect syntax near '>'.
Incorrect syntax near '>'.
At C:\Users\demo\Documents\GitHub\AutomateAPI\Public\Get-ControlSession.ps1:165 char:24
+ ...            $AllData = Invoke-ControlAPIMaster -Arguments $RESTRequest
+                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-ControlAPIMaster

Invoke-ControlAPIMaster : An error has been thrown.
at Invoke-ControlAPIMaster<Process>, C:\Users\demo\Documents\GitHub\AutomateAPI\Public\Invoke-ControlAPIMaster.ps1: line 91
at Get-ControlSession<End>, C:\Users\demo\Documents\GitHub\AutomateAPI\Public\Get-ControlSession.ps1: line 210
at Compare-AutomateControlStatus<End>, C:\Users\demo\Documents\GitHub\AutomateAPI\Public\Compare-AutomateControlStatus.ps1: line 127
at <ScriptBlock>, <No file>: line 1
-->
--> Cannot perform an aggregate function on an expression containing an aggregate or a subquery.
At C:\Users\demo\Documents\GitHub\AutomateAPI\Public\Get-ControlSession.ps1:210 char:28
+ ...            $AllData = Invoke-ControlAPIMaster -Arguments $RESTRequest
+                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-ControlAPIMaster

below is a screenshot from fiddler when it fails:
![Screenshot 2020-12-14 174731](https://user-images.githubusercontent.com/76008419/102149697-a5740e00-3e34-11eb-90d0-049e9f96e953.png)

```

**Comment by DarrenWhite99** [comment]
Do you have the latest master branch code?

The first error (Incorrect syntax near '>'.) I may have seen.
Try logging into Control, and then accessing this URI in your browser: 
/Report.json?ReportType=Session&SelectFields=SessionID&ItemLimit=1
Then if that works, try this:
/Report.json?ReportType=Session&SelectFields=SessionID&SelectFields=IsEnded&ItemLimit=1

The underlying Get-ControlSession function calls for a report and one of the fields it retrieves is "IsEnded".  For one known case, including that field breaks Control and it returns a 500 error.  If that second URI gives you an error, you need to open a ticket with ConnectWise.

As for the second error (Cannot perform an aggregate function on an expression containing an aggregate or a subquery) .... Maybe we just see if the problem is resolved when the IsEnded issue is fixed.

As a workaround kinda, you can edit the definition of $SessionFields in Get-ControlSession (about line 107), just remove IsEnded from the list.  The downside is that if you ask about a session that has been ended you will not be told that it is invalid.  But if that gets you mostly working it might be better than waiting for a code fix. (I spoke to a Control dev today and he stated that the IsEnded handler is part of the code, so it will take a new Control release to resolve it).  The more tickets the better though.

**Comment by codepend** [comment]
The second URI did result in an error,
/Report.json?ReportType=Session&SelectFields=SessionID&SelectFields=IsEnded&ItemLimit=1

I have tried the latest master and the fix verify branch fwiw.

I will try your suggestion as well as open a ticket with CW.

**Comment by codepend** [comment]
So removing the IsEnded from the list of fields resolved the first issue.
The script continues after this and appears to process subsequent requests, i.e. Repair agents etc...

I still receive the following error (despite the script continuing):

Invoke-ControlAPIMaster : An error has been thrown.
at Invoke-ControlAPIMaster<Process>, C:\Users\demo\Documents\GitHub\AutomateAPI\Public\Invoke-ControlAPIMaster.ps1:
line 91
at Get-ControlSession<End>, C:\Users\demo\Documents\GitHub\AutomateAPI\Public\Get-ControlSession.ps1: line 210
at Compare-AutomateControlStatus<End>,
C:\Users\demo\Documents\GitHub\AutomateAPI\Public\Compare-AutomateControlStatus.ps1: line 127
at <ScriptBlock>, <No file>: line 1
-->
--> Cannot perform an aggregate function on an expression containing an aggregate or a subquery.
At C:\Users\demo\Documents\GitHub\AutomateAPI\Public\Get-ControlSession.ps1:210 char:28
+ ...            $AllData = Invoke-ControlAPIMaster -Arguments $RESTRequest
+                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-ControlAPIMaster

This looks to be related to an API call to Control. Here is the Request and Response:

Request:
URI: /App_Extensions/fc234f0e-2e8e-4a1f-b977-ba41b14031f7/ReportService.ashx/GenerateReportForAutomate

BODY: ["SessionConnection",["SessionID"],["LastDisconnectedTime"],"ProcessType=\u0027Guest\u0027 AND (SessionSessionType=\u0027Access\u0027)","",10000]

Reponse (500):
{"errorType":"FaultException<SessionManagerFault>","message":"Cannot perform an aggregate function on an expression containing an aggregate or a subquery.","detail":null}

**Comment by DarrenWhite99** [comment]
The second query is this one:
`/Report.json?ReportType=SessionConnection&GroupFields=SessionID&SelectFields=LastDisconnectedTime&Filter=ProcessType%3D'Guest'%20AND%20(SessionSessionType%3D'Access')&ItemLimit=10000`
.. which I just tested and works fine for me.  

Does that run for you? Honestly, if it throw an error I would try reporting it to ConnectWise since it should be a valid report query.

**Comment by codepend** [comment]
It did not work, run-time error on the page.

I will submit a ticket with CW. 

As far as the "IsEnded" thing, is there some specific language you think I should include when I open a ticket for that one?

**Comment by DarrenWhite99** [comment]
Provide that same info, using the Report.json examples, saying X works, Y doesn't... Darren
-------- Original message --------From: codepend <notifications@github.com> Date: 12/17/20  9:47 AM  (GMT-08:00) To: gavsto/AutomateAPI <AutomateAPI@noreply.github.com> Cc: Darren White <github@darrenwhite.org>, Comment <comment@noreply.github.com> Subject: Re: [gavsto/AutomateAPI] Control requests failing (#54) 
It did not work, run-time error on the page.
I will submit a ticket with CW.
As far as the "IsEnded" thing, is there some specific language you think I should include when I open a ticket for that one?

**Comment by codepend** [comment]
Done, and thank you.

**Comment by codepend** [comment]
I think you can likely close this. In the particular instance this is happening, the client has migrated their Control database to MS SQL from sqllite (or whatever the default native db is) and the SQL used in the failing queries are not syntactically correct in MS SQL. Nothing you can do about this afaik.
